### ISSUE TITLE
Resizing errors

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#233]
0 and negative sizes currently explode in fascinating ways.

Here's the program as written:

```
import ppb
import math

class MyGameObject(ppb.BaseSprite):
    image = "resources/ship.png"
    count = 0

    def on_update(self, update, signal):
        self.count += update.time_delta
        self.size = math.sin(self.count)
        self.rotation += 2
        self.position = ppb.Vector(math.sin(self.count) * 2, math.cos(self.count) * 2)


def setup(scene):
    scene.add(MyGameObject())


ppb.run(setup=setup)
```

I don't know the exact cause of this error, but I managed a seg fault, so that was fun:

```(pygame-install) glgpcadmins-MacBook-Pro:pytexas-livecode piper$ .venv/bin/python main.py 
pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html
2019-04-10 13:19:16.986 Python[17979:1885036] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
Fatal Python error: (pygame parachute) Segmentation Fault

Current thread 0x00007fffb0518380 (most recent call first):
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/systems/__init__.py", line 127 in rotate_image
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/systems/__init__.py", line 82 in prepare_resource
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/systems/__init__.py", line 63 in on_render
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/events.py", line 76 in __event__
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/engine.py", line 115 in publish
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/engine.py", line 93 in main_loop
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/engine.py", line 79 in run
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/__init__.py", line 34 in run
  File "main.py", line 22 in <module>
Abort trap: 6
```

I shrunk the example  a bit, to test specific failure modes:

```
import ppb


class MyGameObject(ppb.BaseSprite):
    size = 0


def setup(scene):
    scene.add(MyGameObject())


ppb.run(setup=setup)
```

And the associated terminal output:

```(pygame-install) glgpcadmins-MacBook-Pro:pytexas-livecode piper$ .venv/bin/python main.py 
pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html
2019-04-10 13:30:41.951 Python[18082:1892028] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    ppb.run(setup=setup)
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/__init__.py", line 34, in run
    eng.run()
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/engine.py", line 79, in run
    self.main_loop()
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/engine.py", line 93, in main_loop
    self.publish()
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/engine.py", line 115, in publish
    system.__event__(event, self.signal)
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/events.py", line 76, in __event__
    meth(bag, fire_event)
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/systems/__init__.py", line 63, in on_render
    resource = self.prepare_resource(game_object)
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/systems/__init__.py", line 81, in prepare_resource
    resized_image = self.resize_image(source_image, game_object.size)
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/systems/__init__.py", line 119, in resize_image
    game_unit_size)
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/systems/__init__.py", line 133, in target_resolution
    ratio = values[short_side_index] / target
ZeroDivisionError: division by zero
```

And with a negative size:

```
import ppb


class MyGameObject(ppb.BaseSprite):
    size = -1


def setup(scene):
    scene.add(MyGameObject())


ppb.run(setup=setup)

```

And the trace:

```
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    ppb.run(setup=setup)
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/__init__.py", line 34, in run
    eng.run()
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/engine.py", line 79, in run
    self.main_loop()
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/engine.py", line 93, in main_loop
    self.publish()
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/engine.py", line 115, in publish
    system.__event__(event, self.signal)
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/events.py", line 76, in __event__
    meth(bag, fire_event)
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/systems/__init__.py", line 63, in on_render
    resource = self.prepare_resource(game_object)
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/systems/__init__.py", line 81, in prepare_resource
    resized_image = self.resize_image(source_image, game_object.size)
  File "/Users/piper/src/pathunstrom/pursuedpybear/ppb/systems/__init__.py", line 121, in resize_image
    target_resolution)
ValueError: Cannot scale to negative size
```

This is all off of f81f327d67c57f25a0686587918cd5e9beb11ec2 with python 3.7 and pygame 1.9.5

**Comment by pathunstrom** [comment]
So this is buried in the renderer, and will mostly be fixed by error handling and reasonable defaults. Good for a new developer to try out.
