### ISSUE TITLE
Playing too many longer sounds causes and SDL channels error

### ISSUE THREAD

**Issue by ironfroggy** [ppb/pursuedpybear#420]
If you play more than 8 sounds at once, which seems to be the default number of channels, there is a non-recoverable error. Maybe this case should fail silently, possibly with a warning rather than an error. Or, an error handling mechanism could let users catch this. Or, the ability to change the number of channels could help the user have more control over the limit.

Most importantly, imho, would be a less-aggressive default failure mode.

```
Traceback (most recent call last):
  File ".\main.py", line 547, in <module>
    resolution=(1080, 800),
  File "c:\users\calvin\gamedev\pursuedpybear\ppb\__init__.py", line 71, in run
    eng.run()
  File "c:\users\calvin\gamedev\pursuedpybear\ppb\engine.py", line 100, in run
    self.main_loop()
  File "c:\users\calvin\gamedev\pursuedpybear\ppb\engine.py", line 111, in main_loop
    self.loop_once()
  File "c:\users\calvin\gamedev\pursuedpybear\ppb\engine.py", line 121, in loop_once
    self.publish()
  File "c:\users\calvin\gamedev\pursuedpybear\ppb\engine.py", line 154, in publish
    method(event, self.signal)
  File "c:\users\calvin\gamedev\pursuedpybear\ppb\systems\sound.py", line 149, in on_play_sound
    _check_error=lambda rv: rv == -1
  File "c:\users\calvin\gamedev\pursuedpybear\ppb\systems\sound.py", line 48, in _call
    raise SdlMixerError(f"Error calling {func.__name__}: {err.decode('utf-8')}")
ppb.systems.sound.SdlMixerError: Error calling <lambda>: No free channels available
```

**Comment by pathunstrom** [comment]
This is related to #394. Would rather just keep these linked for now. Can collapse them into one issue during our next sweep.

**Comment by astronouth7303** [comment]
To be clear: The new behavior is that "the sound will be dropped on the floor and a warning played.
