### ISSUE TITLE
Linux "ppb.systems._sdl_utils.SdlMixerError: Error calling Mix_Init: OGG support not available"

### ISSUE THREAD

**Issue by abixadamj** [ppb/pursuedpybear#502]
I have tried your code from README file (about Ship), and I got an error:

```
Traceback (most recent call last):
  File "ship.py", line 14, in <module>
    ppb.run(setup=setup)
  File "/home/adasiek/.local/lib/python3.6/site-packages/ppb/__init__.py", line 122, in run
    with make_engine(setup, starting_scene=starting_scene, title=title, **engine_opts) as eng:
  File "/home/adasiek/.local/lib/python3.6/site-packages/ppb/engine.py", line 107, in __enter__
    self.start_systems()
  File "/home/adasiek/.local/lib/python3.6/site-packages/ppb/engine.py", line 124, in start_systems
    self.exit_stack.enter_context(system)
  File "/usr/lib/python3.6/contextlib.py", line 330, in enter_context
    result = _cm_type.__enter__(cm)
  File "/home/adasiek/.local/lib/python3.6/site-packages/ppb/systems/sound.py", line 88, in __enter__
    mix_call(Mix_Init, MIX_INIT_FLAC | MIX_INIT_MOD | MIX_INIT_MP3 | MIX_INIT_OGG)
  File "/home/adasiek/.local/lib/python3.6/site-packages/ppb/systems/_sdl_utils.py", line 94, in mix_call
    raise SdlMixerError(f"Error calling {func.__name__}: {err.decode('utf-8')}")
ppb.systems._sdl_utils.SdlMixerError: Error calling Mix_Init: OGG support not available

```
My system is:

```
adasiek@mint-desktop:~/tmp$ python3 
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
adasiek@mint-desktop:~/tmp$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19.3 Tricia
Release:	19.3
Codename:	tricia
adasiek@mint-desktop:~/tmp$ uname -a
Linux mint-desktop 4.15.0-108-generic #109-Ubuntu SMP Fri Jun 19 11:33:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```

I have tried to remark (comment out) every one type in line 88:
`mix_call(Mix_Init, MIX_INIT_FLAC | MIX_INIT_MOD | MIX_INIT_MP3 | MIX_INIT_OGG)`

but with no success.

Python bindings to SDL2 in my system is: 
`ii  python3-sdl2          0.9.3+dfsg2-1   all             Python bindings to the SDL2 C-library (Python 3`
![Zrzut ekranu z 2020-07-20 17-48-12](https://user-images.githubusercontent.com/5088643/87957944-3545a400-cab1-11ea-97ed-6b2ffc890432.png)

**Comment by AstraLuma** [comment]
Linux?

My guess is that the ogg libraries aren't a required dependency on your distro, and you don't have them installed for other reasons. I only checked a few distros when I wrote those instructions.

Long term, I'd like to add Linux binaries to the dependant wheels.

**Comment by bildzeitung** [comment]
I just hit this in WSL2.

I think it's this:
  https://discourse.libsdl.org/t/bug-sdl2-mixer-init-error-format-support-not-available/23705

I reordered the init and open calls and that seems to have done it.

**Comment by AstraLuma** [comment]
😱 

I'm going to have to test this--Assets can be created (and loaded) at any time, so it's impossible to have every `Mix_OpenAudio()` called before `Mix_Init`.

**Comment by bildzeitung** [comment]
Eek! Ok -- I'll throw up the PR with the understanding that it might not be the right thing, but at least it'll be there if it turns out to be ok :)

**Comment by pathunstrom** [comment]
Just replicated this on Windows 10 with python 3.9:

```
(.venv) ppb\pursuedpybear\examples\animated_sprites>python animated_sprite.py
UserWarning: Using SDL2 binaries from pysdl2-dll 2.0.14
Traceback (most recent call last):
  File "ppb\pursuedpybear\examples\animated_sprites\animated_sprite.py", line 27, in <module>
    ppb.run(setup)
  File ".venv\lib\site-packages\ppb\__init__.py", line 125, in run
    with make_engine(setup, starting_scene=starting_scene, title=title, **engine_opts) as eng:
  File ".venv\lib\site-packages\ppb\engine.py", line 276, in __enter__
    self.children.__enter__()
  File ".venv\lib\site-packages\ppb\engine.py", line 197, in __enter__
    self._stack.enter_context(system)
  File "PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 429, in enter_context
    result = _cm_type.__enter__(cm)
  File ".venv\lib\site-packages\ppb\systems\sound.py", line 99, in __enter__
    mix_call(Mix_Init, MIX_INIT_FLAC | MIX_INIT_MOD | MIX_INIT_MP3 | MIX_INIT_OGG)
  File ".venv\lib\site-packages\ppb\systems\sdl_utils.py", line 94, in mix_call
    raise SdlMixerError(f"Error calling {func.__name__}: {err.decode('utf-8')}")
ppb.systems.sdl_utils.SdlMixerError: Error calling Mix_Init: OGG support not available
```

I ran the animated sprite example with a fresh 3.9 virtual environment only install was `pip install ppb`.

**Comment by bildzeitung** [comment]
With respect to WSL, I'm *really* hoping that the init / sound / driver issues are resolved in the upcoming support for X apps: https://github.com/microsoft/wslg . I'll try to test whenever I get a computer on the preview release, but 🤞

**Comment by AstraLuma** [comment]
Even if they don't, PPB should work without wsl.

**Comment by bildzeitung** [comment]
Fair enough; won't see me arguing that.

I suppose the broader concern is whether PPB should work without audio if there ain't any. Not sure if the asset loading has been re-worked to sort out the init issues -- it's been a while since I dug into that stuff.

That being said, the WSL experience is pretty miserable (not due to PPB) for a bunch of reasons -- a bunch of add'l setup notwithstanding, so I thought I'd at least mention that the experience might be getting more stable (audio seemed particularly prone to failure and I while I had a procedure where it would work .. it would work *just once* and then involved stopping / starting daemons and I didn't think that'd be a good thing to even try to advertise, given PPB's goals). Of course, I ought to have mentioned that as a follow-on to the comments above but that dropped on the floor -- & for that I apologize.

**Comment by pathunstrom** [comment]
A good thing to note: We should see how the new SDL wheels affect WSL when we get a chance.

**Comment by AstraLuma** [comment]
I'm hoping that pysdl2-dll shipping Linux fixes this.
