### ISSUE TITLE
SdlMixerError error when running ppb

### ISSUE THREAD

**Issue by ace510** [ppb/pursuedpybear#676]
'''
UserWarning: Using SDL2 binaries from pysdl2-dll 2.24.0
Traceback (most recent call last):
  File "C:\Users\ihclark\Python-2022-9-30\ppb_gam.py", line 3, in <module>
    ppb.run()
  File "C:\Python39\lib\site-packages\ppb\__init__.py", line 152, in run
    with make_engine(setup, starting_scene=starting_scene, title=title, **engine_opts) as eng:
  File "C:\Python39\lib\site-packages\ppb\engine.py", line 292, in __enter__
    self.children.__enter__()
  File "C:\Python39\lib\site-packages\ppb\engine.py", line 213, in __enter__
    self._stack.enter_context(system)
  File "C:\Python39\lib\contextlib.py", line 429, in enter_context
    result = _cm_type.__enter__(cm)
  File "C:\Python39\lib\site-packages\ppb\systems\sound.py", line 127, in __enter__
    mix_call(Mix_Init, MIX_INIT_FLAC | MIX_INIT_MOD | MIX_INIT_MP3 | MIX_INIT_OGG)
  File "C:\Python39\lib\site-packages\ppb\systems\sdl_utils.py", line 94, in mix_call
    raise SdlMixerError(f"Error calling {func.__name__}: {err.decode('utf-8')}")
ppb.systems.sdl_utils.SdlMixerError: Error calling Mix_Init: Failed loading ModPlug_Tell: The specified procedure could not be found.
'''

error happens with Python 3.9.5 on 64 bit WIn 10 21H1

Code to reproduce:
'''
import ppb

ppb.run()
'''

**Comment by troberts-28** [comment]
Did you have any luck with this?

**Comment by ace510** [comment]
worked a treat! thank you
